apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacityshubli
  labels:
    app: udacityshubli
    
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: udacityshubli
  template:
    metadata:
      labels:
        app: udacityshubli
        
    spec:
      containers:
      - name: udacityshubli
        image: shublirafat/udacityshubli
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  
---
apiVersion: v1
kind: Service
metadata:
  name: udacityshubli-2
  labels:
    app: udacityshubli
    
spec:
  selector:
    app: udacityshubli
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer